services:
  server-power-watchdog:
    image: ghcr.io/turge08/server-power-watchdog:main
    container_name: server-power-watchdog
    ports:
      - "8080:8080"
      - "3493:3493"
    volumes:
      - ~/server_power_watchdog/data:/config/data
      - /dev/bus/usb:/dev/bus/usb
    restart: unless-stopped
