services:
  server-power-watchdog:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: server-power-watchdog
    ports:
      - "8080:8080"
      - "3493:3493"
    volumes:
      - ../data:/config/data
      - /dev/bus/usb:/dev/bus/usb
    restart: unless-stopped
